### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by JuraBu** [pezinek/ote2csv#1]
Hello,
I was intrigued and could see a use for me at home.
I try it, but it's end with error. 

_s:\ote2csv-main>ote_dump.py
Traceback (most recent call last):
  File "S:\ote2csv-main\ote_dump.py", line 142, in <module>
    dump_all_data(session, 'ote_prices.csv', start_date=datetime(year=2002, month=1, day=1))
  File "S:\ote2csv-main\ote_dump.py", line 122, in dump_all_data
    while cur_date < end_date:
          ^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'__

Can you help me with this error, please?

**Comment by pezinek** [comment]
Sorry for this, was a mistake I created when implementing the incremental downloads feature, forgot to check the code still works if you start fresh and don't have any previous data to append the incremental download to. 
Should be fixed now.
